# Generated by Django 5.0.3 on 2024-04-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField(max_length=6)),
                ('address', models.CharField(max_length=300)),
                ('phone_no', models.IntegerField(max_length=10)),
            ],
        ),
    ]
