# Generated by Django 5.0.3 on 2024-04-12 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
